# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "bold blue"
truncation_length = 2
truncate_to_repo = true

[line_break]
disabled = true

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[package]
disabled = true

[aws]
disabled = true

[python]
disabled = true

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_status]
disabled = true
