# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# Disable the package module, hiding it from the prompt completely

[line_break]
disabled = true


[package]
disabled = true

[aws]
disabled = true

[python]
disabled = true

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_status]
disabled = true
