def gui_enabled?
  ENV.fetch('GUI', 'false') == true
end

Vagrant.configure(2) do |config|
  config.vm.box = "Win10"
  config.vm.guest = :windows
  config.vm.communicator = "winrm"
  config.vm.boot_timeout = 600
  config.vm.graceful_halt_timeout = 600

  config.vm.network :forwarded_port, guest: 8800, host: 8800
  config.vm.network :forwarded_port, guest: 8808, host: 8808
  config.vm.network :forwarded_port, guest: 1433, host: 1433

  config.vm.synced_folder "../../../xencube", "/Workspace/xencube"

  config.vm.provider "virtualbox" do |vm|
      vm.name = "windows10-pc"
      vm.gui = gui_enabled?
      vm.cpus = 2
      vm.memory = 5120
  end
end
