---
- name: add repository
  apt_repository:
    repo: 'ppa:neovim-ppa/unstable'
    state: present
    update_cache: yes

- name: install neovim
  apt:
    name: neovim
    state: present
    update_cache: yes
