---
- name: include install tasks
  include_tasks: "{{ ansible_os_family|lower }}.yaml"

- name: install python2 pynvim
  pip:
    name: neovim
    executable: pip2

- name: install python3 pynvim
  pip:
    name: neovim
    executable: pip3

- name: create necessary directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ config_dir }}"
    - "{{ autoload_dir }}"
    - "{{ plugin_dir }}"

- name: Create a symbolic link of init.vim
  file:
    src: "{{ dotfiles_dir }}/init.vim"
    dest: "{{ config_file }}"
    force: yes
    state: link

- name: Create a symbolic link of COC settings 
  file:
    src: "{{ dotfiles_dir }}/coc-settings.json"
    dest: "{{ config_dir }}/coc-settings.json"
    force: yes
    state: link

- name: download vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ autoload_dir }}/plug.vim"

- name: install plugins
  command: nvim +'PlugInstall --sync' +qa
