---
- name: include install tasks
  include_tasks: "{{ ansible_os_family|lower }}.yaml"

- name: install python2 pynvim
  pip:
    name: neovim
    executable: pip2

- name: install python3 pynvim
  pip:
    name: neovim
    executable: pip3

- name: create necessary directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ config_dir }}"
    - "{{ autoload_dir }}"
    - "{{ plugin_dir }}"

- name: deploy config file
  template:
    src: "init.vim.j2"
    dest: "{{ config_file }}"

- name: download vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ autoload_dir }}/plug.vim"

- name: install plugins
  command: nvim +'PlugInstall --sync' +qa
