version: "2"

services:
  janusgraph:
    image: janusgraph/janusgraph:latest
    container_name: janusgraph-local
    ports:
      - "8182:8182"
    volumes:
      # Named volume mounts. The data mount is only used when BerkeleyDB is used for storage.
      - "janusgraph-data:/var/lib/janusgraph/data"
      - "janusgraph-index:/var/lib/janusgraph/index"
      # bind mounts for configs; use read only so not overridden by environment variables
      - "./janusgraph-config:/etc/opt/janusgraph/:ro"
    networks:
      - janusnet

# use a named volume to maintain database data between restarts
volumes:
  janusgraph-data:
    driver: local
  janusgraph-index:
    driver: local

networks:
  janusnet:
    driver: bridge

