version: "2"

services:
    pgAdmin:
        restart: always
        image: dpage/pgadmin4
        container_name: "pgadmin"
        ports:
            - "8000:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@localhost.com
            PGADMIN_DEFAULT_PASSWORD: 123
        volumes:
            - pgadmin:/var/lib/pgadmin
        networks:
          - postgres
    postgres:
        restart: always
        image: postgres
        container_name: "postgres"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: 123
            POSTGRES_DB: postgres
        volumes:
            - postgres:/var/lib/postgresql/data
        networks:
          - postgres
volumes:
    postgres:
    pgadmin:

networks:
  postgres:
    driver: bridge
