---
- name: install git
  homebrew:
      name: git
      state: present

- name: install python 2
  homebrew:
    name: python
    state: present

- name: install python3
  homebrew:
    name: python3
    state: present

- name: install fzf
  homebrew:
    name: fzf
    state: present

- name: configure fzf
  shell: "$(brew --prefix)/opt/fzf/install --all"
