---
- name: install git
  apt:
    name: git
    state: present
  become: yes

- name: install python
  apt:
    name: python,python3,python-dev,python-pip,python3-dev,python3-pip
    state: present
  become: yes
