---
- name: install git
  apt:
    name: git
    state: present
  become: yes

- name: install python
  apt:
    name: python,python3,python-dev,python-pip,python3-dev,python3-pip
    state: present
  become: yes
- name: nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"